tasks:
  - init: eval $(gp env -e) && npm install
  - command: export TZ="Asia/Tokyo"
  - command: npm run serve
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
